name: documenso-test

services:
  database:
    image: postgres:15
    volumes:
      - documenso_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=documenso
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U documenso']
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - 54322:5432

  inbucket:
    image: inbucket/inbucket
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100

  documenso:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      inbucket:
        condition: service_started
    env_file:
      - ../../.env.example
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXT_PRIVATE_ENCRYPTION_KEY=CAFEBABE
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=DEADBEEF
      - NEXT_PRIVATE_DATABASE_URL=postgres://documenso:password@database:5432/documenso
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:password@database:5432/documenso
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=database
      - NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
      - NEXT_PRIVATE_SMTP_HOST=inbucket
      - NEXT_PRIVATE_SMTP_PORT=2500
      - NEXT_PRIVATE_SMTP_USERNAME=documenso
      - NEXT_PRIVATE_SMTP_PASSWORD=password
      - NEXT_PRIVATE_SMTP_FROM_NAME="No Reply @ Documenso"
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=noreply@documenso.com
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/cert.p12
    ports:
      - 3000:3000
    volumes:
      - ../../certs/cert.p12:/opt/documenso/cert.p12

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: documenso
      MINIO_ROOT_PASSWORD: password
    entrypoint: sh
    command: -c 'mkdir -p /data/documenso && minio server /data --console-address ":9001" --address ":9002"'

  adminer:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_LISTEN_PORT: '5050'
    depends_on:
      - database
    ports:
      - '${FORWARD_PGADMIN_PORT:-5050}:5050'
    volumes:
      - pgadmin-data-documenso:/var/lib/pgadmin

volumes:
  pgadmin-data-documenso:
  minio:
  documenso_database:
